[[redirects]]
  from = "/embed/volume/*"
  to = "https://juice-tools-embed-volume.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/embed/balance/*"
  to = "https://juice-tools-embed-balance.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/embed/pay/*"
  to = "https://juice-tools-embed-pay.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/pay.js"
  to = "/public/dist/pay.js"

[functions]
  directory = "netlify/functions"